Test update to kubernetes-client-api 5.x
jenkinsci/kubernetes-credentials-provider-plugin pull request #54
Opened 2021-06-10 12:12 UTC by Vlatombe

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-06-10 13:35 UTC, Vlatombe commented
Not sure what has changed but I'm getting similar failures on master.

2021-06-15 12:52 UTC, Vlatombe commented on pom.xml
> +        <version>2.12.1</version>
```suggestion
        <version>2.12.3</version>

```

2021-06-15 12:52 UTC, Vlatombe commented on pom.xml
> +      <version>5.4.1-beta-1</version>
```suggestion
      <version>5.4.1</version>

```

2021-06-15 12:54 UTC, Vlatombe commented
This pull request should be merged and released in order to achieve compatibility with [kubernetes-client-api 5.4.1](https://github.com/jenkinsci/kubernetes-client-api-plugin/releases/tag/kubernetes-client-api-5.4.1).

2021-06-23 06:37 UTC, topikachu commented
I have an issue when start Jenkins
```
java.lang.NoSuchMethodError: io.fabric8.kubernetes.client.dsl.FilterWatchListDeletable.watch(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.KubernetesCredentialProvider.startWatchingForSecrets(KubernetesCredentialProvider.java:128)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
```

Kubernetes Client API Plugin 5.4.1
Kubernetes Credentials Provider 0.18-1
Jenkins 2.289.1

2021-06-23 07:51 UTC, Vlatombe commented
@topikachu you should revert Kubernetes Client API Plugin until this plugin catches up.

2021-06-23 07:52 UTC, Vlatombe commented
@jtnord fyi

2021-06-23 08:32 UTC, jtnord approved these changes

2021-06-23 08:34 UTC, jtnord commented
@Vlatombe Jenkins reports test failures

2021-06-23 08:36 UTC, Vlatombe commented
> @Vlatombe Jenkins reports test failures

https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/pull/54#issuecomment-858628876

2021-06-23 10:58 UTC, jtnord commented
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8202343

Oh clucking bell.....

2021-06-23 11:03 UTC, jtnord commented
@Vlatombe  I ran the tests locally on master and they pass, 2 tests fail with this PR.  (just use a JDK older than 8u291)

```
[ERROR] Tests run: 25, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.02 s <<< FAILURE! - in com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.SecretUtilsTest
[ERROR] com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.SecretUtilsTest.getNonNullSecretDataWithNoData  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
        at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.SecretUtils.getNonNullSecretData(SecretUtils.java:200)
        at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.SecretUtilsTest.getNonNullSecretDataWithNoData(SecretUtilsTest.java:189)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

[ERROR] com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.SecretUtilsTest.getNonNullSecretDataWithNoMappedData  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
        at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.SecretUtils.getNonNullSecretData(SecretUtils.java:202)
        at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.SecretUtilsTest.getNonNullSecretDataWithNoMappedData(SecretUtilsTest.java:202)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

```

2021-06-23 11:08 UTC, jtnord requested changes
2 new test failures unrelated to the TLS negotiotion/

2021-06-23 11:37 UTC, Vlatombe commented
> 2 new test failures unrelated to the TLS negotiotion/

Fixed. Indeed, kubernetes-client made some changes in their fluent api generator that needed adjustment.

2021-06-23 17:11 UTC, merged

2021-06-23 17:11 UTC, jtnord commented
thanks @Vlatombe

2021-06-23 17:29 UTC, jtnord commented
released [kubernetes-credentials-provider-0.20](https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/releases/tag/kubernetes-credentials-provider-0.20)