Bump to 6.8.1 of kubernetes-client-api-plugin
jenkinsci/kubernetes-credentials-provider-plugin pull request #78
Opened 2023-08-17 12:30 UTC by julieheard

Downstream of https://github.com/jenkinsci/kubernetes-client-api-plugin/pull/221 When the PR for kubernetes-client-api-plugin is merged and we get a new release, we need to check the new version number againt what I have put in the pom for the version number on this plugin.

I ran mvn verify to test locally and all working, all tests passing

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-08-21 15:40 UTC, rsandell commented on pom.xml
> +      <version>2.0-999999-SNAPSHOT</version>
An incremental version was deployed https://ci.jenkins.io/job/Plugins/job/snakeyaml-api-plugin/job/PR-94/1/pipeline-console/ but how to figure out what that version is I don't know.

2023-08-21 15:43 UTC, rsandell commented on pom.xml
> +      <version>2.0-999999-SNAPSHOT</version>
Found it!
```suggestion
      <version>2.1-110.v4960f4074978</version>    
```

2023-08-29 13:28 UTC, Vlatombe commented on pom.xml
> +      <version>6.8.1-220.v1f66736f9a_42</version>
```suggestion
      <version>6.8.1-224.vd388fca_4db_3b_</version>
```

2023-08-29 13:53 UTC, Vlatombe commented
@julieheard Need to bump `jenkins.version` here.
```
[2023-08-29T13:30:25.903Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Dependency org.jenkins-ci.plugins:kubernetes-client-api:jar:6.8.1-224.vd388fca_4db_3b_ requires Jenkins 2.401.1 or higher.
```

2023-08-29 14:59 UTC, Vlatombe commented
@julieheard I can't update this PR so you need to fix it.

2023-08-29 15:05 UTC, julieheard commented
I am on it, when testing locally it also wants bumps for bouncycastle-api:2.27, okhttp-api:4.10.0-132.v7a_7b_91cef39c and jackson2-api:2.15.1-344.v6eb_55303dc3e

2023-08-29 17:00 UTC, julieheard commented
Ok to fix this I had to:

2023-08-29 17:07 UTC, julieheard commented
Due to the Jenkins bump I have also bumped Kotlin and included three new dependencies (bouncycastle-api, jackson2-api, okhttp-api) as they were creating RequireUpperBoundDeps errors.

I came accross a strange issue with a test, `mvn verify` it was failing intermittently with this message:
```
[ERROR] Tests run: 10, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.661 s <<< FAILURE! -- in com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.convertors.CertificateCredentialsConvertorTest
[ERROR] com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.convertors.CertificateCredentialsConvertorTest.failsToConvertWhenCertificateCorruptBase64 -- Time elapsed: 0.015 s <<< ERROR!
java.lang.NoSuchMethodError: 'org.hamcrest.Matcher org.hamcrest.CoreMatchers.allOf(org.hamcrest.Matcher, org.hamcrest.Matcher)'
[ERROR] com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.convertors.CertificateCredentialsConvertorTest.failsToConvertWhenCertificateCorruptPKCS12 -- Time elapsed: 0.006 s <<< ERROR!
java.lang.NoSuchMethodError: 'org.hamcrest.Matcher org.hamcrest.CoreMatchers.allOf(org.hamcrest.Matcher, org.hamcrest.Matcher)'
```
Digging into this I think it is a conflict between junit and hamcrest, I do not think it is due to the changes made in this PR.

2023-08-30 07:22 UTC, Vlatombe commented
```
java.lang.NoSuchMethodError: 'org.hamcrest.Matcher org.hamcrest.CoreMatchers.allOf(org.hamcrest.Matcher, org.hamcrest.Matcher)'
```

Can't reproduce on my side, and I only see one hamcrest copy in the classpath (through junit)

```
+- junit:junit:jar:4.13.2:test
|  \- org.hamcrest:hamcrest-core:jar:2.2:test
+- org.hamcrest:hamcrest:jar:2.2:test
```

2023-08-30 12:13 UTC, julieheard commented
I have re-ran this test quite a few times today and also now can't reproduce. Must have been a small glitch in the classpath or something silly. Hopefully this PR is now ready to merge 🙂

2023-09-04 13:53 UTC, jtnord requested changes

2023-09-04 13:53 UTC, jtnord commented on pom.xml
> +    </dependency>
I do not depend on these and so they should not be needed.   What is the rationale for the the creep in dependencies?

perhaps you just need to pickup a newer bom version?

2023-09-04 15:17 UTC, jtnord approved these changes

2023-09-04 15:17 UTC, merged